### ISSUE TITLE
Doesn't work in (modern) versions of IE (11)

### ISSUE THREAD

**Issue by Oj18** [oojmed/TxtToSL-Web#1]

**Comment by RamanaVem** [comment]
Hey @Oj18 can i take a look on this. And can you give me details, what is not working in IE11.

**Comment by Oj18** [comment]
I don't have access to IE right now, but I know that the centering of the entire app isn't working and that when you try and translate / press enter it just refreshes due to the form.

I might boot up a VM and try and fix this myself, if you don't mind.

**Comment by RamanaVem** [comment]
Ok that's cool, But can i look for centering content.
